# Nombre de la aplicacion
spring.config.import=optional:file:.env[.properties]
spring.application.name=devs
spring.liquibase.enabled=false
# Servidor
server.port=8085

# Base de datos SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1334;databaseName=nprueba;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=QuieroSaber76!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
application.security.jwt.secret-key=12345678901234567890123456789012
application.security.jwt.expiration=862400000
application.security.jwt.refresh-token.expiration=604800000
