# Importación dual tolerante a rutas de ejecución
spring.config.import=optional:file:.env[.properties], optional:file:./devs/devs/.env[.properties]
spring.application.name=devs
spring.liquibase.enabled=false
# Servidor
server.port=8085

# Base de datos SQL Server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD:${db_password}}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT (Búsqueda dual: Variable de entorno o clave plana)
application.security.jwt.secret-key=${JWT_TOKEN:${jwt_token}}
application.security.jwt.expiration=${JWT_EXPIRATION:${jwt_expiration}}
application.security.jwt.refresh-token.expiration=${JWT_EXPIRATION_REFRESH:${jwt_expiration_refresh}}