driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

url: jdbc:sqlserver://sql-server-container:1433;databaseName=DB;encrypt=true;trustServerCertificate=true

username: sa

password: contraseña-que-tenga

changeLogFile: master.xml

logLevel: info

databaseChangeLogTableName: DATABASECHANGELOG
databaseChangeLogLockTableName: DATABASECHANGELOGLOCK